version: "3.8"

services:

  pavepo-api:
    container_name: pavepo-api
    build: ./src
    volumes:
      - ./media:/usr/app/media
    ports:
      - 8000:8000
    environment:
      DEBUG: ${DEBUG}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      JWT_ALGO: ${JWT_ALGO}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      JWT_ACCESS_EXP_SEC: ${JWT_ACCESS_EXP_SEC}
      JWT_REFRESH_EXP_SEC: ${JWT_REFRESH_EXP_SEC}
      ORIGINS: ${ORIGINS}
      ALLOWED_EXTENTIONS: ${ALLOWED_EXTENTIONS}
    depends_on:
      - pavepo-db

  pavepo-db:
    container_name: pavepo-db
    image: postgres:16
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - v_pavepo_db:/var/lib/postgresql/data

volumes:
  v_pavepo_db:
