"""init

Revision ID: 0f2a323de41c
Revises: 1535516ac716
Create Date: 2025-03-31 14:41:08.291030

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0f2a323de41c'
down_revision: Union[str, None] = '1535516ac716'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('files', sa.Column('path', sa.String(), nullable=False))
    op.alter_column('sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('user_external_oauths', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.alter_column('user_external_oauths', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_external_oauths', 'external_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_external_oauths', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('sessions', 'expires_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('sessions', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_column('files', 'path')
    # ### end Alembic commands ###
